- name: Install dependencies for Master
  hosts: Master
  become: yes
  gather_facts: True
  tasks:
  - name: update 
    shell: sudo apt update && sudo apt upgrade -y
  - name: jenkins resources
    shell: wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
  - name: jenkins resources
    shell: sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
  - name: update with new packages
    shell: sudo apt update  
  - name: install java
    shell: sudo apt install default-jre -y
  - name: install jenkins
    shell: sudo apt install jenkins -y
  - name: start jenkins
    shell: sudo systemctl start jenkins

- name: Install Java for Test
  hosts: Test
  become: yes
  gather_facts: True
  tasks:
  - name: update
    shell: sudo apt update && sudo apt upgrade -y
  - name: install java
    shell: sudo apt install default-jre -y
  - name: install needed modules
    shell: sudo apt-get install \ ca-certificates \ curl \ gnupg \ lsb-release
  - name: add dockers key
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - name: stable repo
    shell:  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - name: update packages
    shell: sudo apt update    
  - name: install docker engine
    shell: sudo apt install docker-ce \ docker-ce-cli \ containerd.io -y
    
- name: Install Java and Docker for Prod
  hosts: Prod
  become: yes
  gather_facts: True
  tasks:
  - name: update
    shell: sudo apt update && sudo apt upgrade -y
  - name: install java 
    shell: sudo apt install default-jre -y 
  - name: install needed modules
    shell: sudo apt-get install \ ca-certificates \ curl \ gnupg \ lsb-release
  - name: add dockers key
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - name: stable repo
    shell:  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - name: update packages
    shell: sudo apt update    
  - name: install docker engine
    shell: sudo apt install docker-ce \ docker-ce-cli \ containerd.io -y
