---
- name: "Setting up local machine"
  hosts: localhost
  connection: local
  vars:
    ssh_key_filename: deployment8
    ec2_key: AWStutorials.cer
    controller_ip: 3.82.189.170
    agent_ip: 3.83.246.174
    production_ip: 3.82.220.40

  tasks:
    - name: generate SSH key "{{ssh_key_filename}}"
      openssh_keypair:
        path: "~/.ssh/{{ssh_key_filename}}"
        type: rsa
        size: 4096
        state: present
        force: no
    - name: moving public key onto all ec2s
      command: "{{item}} chdir=~/.ssh"
      with_items:
        - scp -i {{ec2_key}} {{ssh_key_filename}}.pub ubuntu@{{controller_ip}}:/home/ubuntu/.ssh
        - scp -i {{ec2_key}} {{ssh_key_filename}}.pub ubuntu@{{agent_ip}}:/home/ubuntu/.ssh
        - scp -i {{ec2_key}} {{ssh_key_filename}}.pub ubuntu@{{production_ip}}:/home/ubuntu/.ssh

