---
- name: Install git, javascript, and java on Agents
  # become sudo
  become: true
  hosts: Agents
  gather_facts: false
  tasks:
  - name: Install Git 
    apt:
      name: git
  
  # Python by default is installed on Ubuntu AMIs 

  - name: Install nodejs and npm
    apt:
      update_cache: yes
      pkg:
      - nodejs
      - npm

  - name: Install java
    apt:
      pkg:
      - openjdk-11-jdk

  - name: Install xvfb # needed for cypress to run
    apt:
      pkg:
      - xvfb

- name: Install stress on production EC2
  become: true 
  hosts: Production 
  gather_facts: false
  tasks:
  - name: Install stress 
    apt:
      name: stress-ng