---
- name: Install git, javascript, and java on Agents
  # become sudo
  become: true
  hosts: Agents
  gather_facts: false
  tasks:
  - name: Install Git 
    apt:
      name: git
  
  # Python by default is installed on Ubuntu AMIs 

  - name: Install nodejs and npm
    apt:
      update_cache: yes
      pkg:
      - nodejs
      - npm

  - name: Install java
    apt:
      pkg:
      - openjdk-11-jdk

  - name: Install cypress dependencies # needed for cypress to run
    apt:
      pkg:
      - xvfb
      - libgtk2.0-0
      - libgtk-3-0
      - libgbm-dev
      - libnotify-dev
      - libgconf-2-4
      - libnss3
      - libxss1
      - libasound2
      - libxtst6
      - xauth

- name: Install stress on production EC2
  become: true 
  hosts: Production 
  gather_facts: false
  tasks:
  - name: Install stress 
    apt:
      name: stress-ng