- name: Make Security Groups
  hosts: localhost
  gather_facts: false
  vars:
    region: us-east-1
    tenancy: default #set to dedicated if you are working with PHI. It sets all Ec2 in said VPC to work on same phyiscal machine
    key: usedFor
    value: testing
  vars_files:
    - './variables/network_id.yaml'
  tasks:
  - name: Get my public IP
    community.general.ipify_facts:
    register: ipify_public_ip
  - name: register IP as variable
    set_fact:
      publicIP: '{{ipify_public_ip.ansible_facts.ipify_public_ip}}'
  - debug: var=publicIP
  - name: Jenkins SG GROUP
    amazon.aws.ec2_group:
      name: Jenkins
      description: Allows User access to SSH and WebGUI
      vpc_id: '{{vpcid}}' 
      region: '{{region}}'
      rules:
        - proto: tcp
          from_port: 8080
          to_port: 8080
          cidr_ip: "{{ publicIP + '/32' }}"
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: "{{ publicIP + '/32' }}"
  - name: Grab SG1 ID
    amazon.aws.ec2_group_info:
      filters:
        group-name: Jenkins
    register: sg1
  - name: JenkinsAgent SG GROUP
    amazon.aws.ec2_group:
      name: JenkinsAgent
      description: Jenkins SSH Access for Jenkins Main
      vpc_id: '{{vpcid}}' 
      region: '{{region}}'
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: "{{vpcBlock}}"
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: "{{ publicIP + '/32' }}"
  - name: Grab SG2 ID
    amazon.aws.ec2_group_info:
      filters:
        group-name: JenkinsAgent
    register: sg2
  - name: Make Docker SG Group
    amazon.aws.ec2_group:
      name: Docker
      description: For Docker Access via SSH
      vpc_id: '{{vpcid}}' 
      region: '{{region}}'
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: "{{vpcBlock}}"
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: "{{ publicIP + '/32' }}"
  - name: Grab SG3 ID
    amazon.aws.ec2_group_info:
      filters:
        group-name: Docker
    register: sg3
  - name: Assigns sgX_ID as variable
    set_fact: 
      SG1_ID: '{{sg1.security_groups[0].group_id}}'
      SG2_ID: '{{sg2.security_groups[0].group_id}}'
      SG3_ID: '{{sg3.security_groups[0].group_id}}'
  - name: Saving variables to file
    lineinfile:
      path: ./variables/SG_id.yaml
      line: "{{ item }}"
      create: yes
    with_items:
      -  "{{ 'sgid_1:' + ' ' + SG1_ID }}"
      -  "{{ 'sgid_2:' + ' ' + SG2_ID }}"
      -  "{{ 'sgid_3:' + ' ' + SG3_ID }}"