FROM ubuntu:latest
RUN apt-get update && apt-get install -y
COPY ./public /home/ubuntu/application/
COPY ./src /home/ubuntu/application/
COPY ./package-lock.json /home/ubuntu/application/
COPY ./package.json /home/ubuntu/application/
WORKDIR /home/ubuntu/application/
RUN apt-get update && apt-get install -y
RUN apt-get install nodejs npm -y
RUN npm install
RUN npm run build
RUN npm install -g serve
EXPOSE 3000
CMD ["serve", "-s", "build"] 