pipeline {
    agent {
        label "agent"
    }
    stages {
        stage('Build') { 
            steps { 
                sh '''
                   cd application
                   ls
                   pwd
                   '''
                sh 'echo "completed build"'
            }
        }
    }
}
