pipeline {
    agent {
        label "agent"
    }

    environment {
        DOCKERHUB_CREDENTIALS = credentials("rixardo-dockerhub")
    }

    stages {
        // Creating the front end application using NPM
        stage('Build') { 
            steps { 
                sh '''
                cd application/frontend/
                npm install
                npm run build
                sudo npm install -g serve
                serve -s build &
                '''
                sh 'echo "completed build"'
            }
        }
        // Testing the front end application
        stage('Test') { 
            steps { 
                sh '''
                npm install cypress
                npm install mocha
                sudo apt install npm xvfb libatk1.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth -y
                npx cypress run --spec ./cypress/integration/test.spec.js
                '''
                sh 'echo "completed build"'
            }
            post {
                always {
                junit 'results/cypress-report.xml'
                }
            }
        }

        stage('Packaging') { 
            steps {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                sh 'echo "completed login"'
            
                sh 'docker build -f ./application/frontend . -t rixardo/deploy08-frontend:latest'
                sh 'echo "completed building front-end application"'

                sh 'docker push rixardo/deploy08-frontend:latest'
                sh 'echo "completed pushing front-end application"'

                sh 'docker build -f ./application/backend . -t rixardo/deploy08-backend:latest'
                sh 'echo "completed building back-end application"'

                sh 'docker push rixardo/deploy08-backend:latest'
                sh 'echo "completed pushing back-end application"'

            }
            post {
                always {
                junit 'results/cypress-report.xml'
                }
            }
        }
    }
}
